#!/usr/bin/env bash

sudo apt-get install ros-melodic-hector-mapping ros-melodic-amcl ros-melodic-map-server ros-melodic-move-base  ros-melodic-rosserial-python ros-melodic-hls-lfcd-lds-driver ros-melodic-serial ros-melodic-dwa-local-planner
cd ~/catkin_ws/
git clone https://github.com/hussamayoub/turtlebot3melodic.git
cp -r turtlebot3melodic/turtle* src/
rm -rf turtlebot3melodic/
catkin_make

 export ROS_MASTER_URI='http://localhost:11311'
 export ROS_IP=0.0.0.0
 source /opt/ros/melodic/setup.bash
 source /home/ros/catkin_ws/devel/setup.bash


roslaunch turtlebot3_gazebo turtlebot3_maze.launch
